# Site settings
title: atpaino's personal site
email: atpaino@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alex Paino's Personal Site and Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://atpaino.com" # the base hostname & protocol for your site
twitter_username: atpaino
github_username:  atpaino

# Build settings
markdown: kramdown
